# Generated by Django 5.0.2 on 2024-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='name')),
                ('description', models.CharField(max_length=240, verbose_name='description')),
                ('rental_price', models.FloatField(default=999.99, verbose_name='rental_price')),
                ('rented_user_id', models.IntegerField(verbose_name='rented_user_id')),
            ],
        ),
    ]
