# Generated by Django 5.0.2 on 2024-02-24 02:56

import bike.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=bike.models.default_profile_picture, null=True, upload_to='profile_pics/'),
        ),
    ]
