# Generated by Django 5.0.2 on 2024-02-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='rental_period',
            field=models.IntegerField(default=1, verbose_name='rental_period'),
        ),
    ]
